@echo off

echo "
📦 Initializing Kubernetes cluster...
"
minikube "start" "--cpus" "2" "--memory" "4g" "--driver" "docker" "--profile" "polar"
echo "
🔌 Enabling NGINX Ingress Controller...
"
minikube "addons" "enable" "ingress" "--profile" "polar"
sleep "15"
echo "
📦 Deploying Keycloak..."
kubectl "apply" "-f" "services\keycloak-config.yml"
kubectl "apply" "-f" "services\keycloak.yml"
sleep "5"
echo "
⌛ Waiting for Keycloak to be deployed..."
REM UNKNOWN: {"type":"While","clause":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"[","type":"Word"},"suffix":[{"text":"$(kubectl get pod -l app=polar-keycloak | wc -l)","expansion":[{"loc":{"start":0,"end":47},"command":"kubectl get pod -l app=polar-keycloak | wc -l","type":"CommandExpansion","commandAST":{"type":"Script","commands":[{"type":"Pipeline","commands":[{"type":"Command","name":{"text":"kubectl","type":"Word"},"suffix":[{"text":"get","type":"Word"},{"text":"pod","type":"Word"},{"text":"-l","type":"Word"},{"text":"app=polar-keycloak","type":"Word"}]},{"type":"Command","name":{"text":"wc","type":"Word"},"suffix":[{"text":"-l","type":"Word"}]}]}]}}],"type":"Word"},{"text":"-eq","type":"Word"},{"text":"0","type":"Word"},{"text":"]","type":"Word"}]}]},"do":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"sleep","type":"Word"},"suffix":[{"text":"5","type":"Word"}]}]}}
echo "
⌛ Waiting for Keycloak to be ready..."
kubectl "wait" "--for=condition=ready" "pod" "--selector=app=polar-keycloak" "--timeout=300s"
echo "
📦 Deploying PostgreSQL..."
kubectl "apply" "-f" "services\postgresql.yml"
sleep "5"
echo "
⌛ Waiting for PostgreSQL to be deployed..."
REM UNKNOWN: {"type":"While","clause":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"[","type":"Word"},"suffix":[{"text":"$(kubectl get pod -l db=polar-postgres | wc -l)","expansion":[{"loc":{"start":0,"end":46},"command":"kubectl get pod -l db=polar-postgres | wc -l","type":"CommandExpansion","commandAST":{"type":"Script","commands":[{"type":"Pipeline","commands":[{"type":"Command","name":{"text":"kubectl","type":"Word"},"suffix":[{"text":"get","type":"Word"},{"text":"pod","type":"Word"},{"text":"-l","type":"Word"},{"text":"db=polar-postgres","type":"Word"}]},{"type":"Command","name":{"text":"wc","type":"Word"},"suffix":[{"text":"-l","type":"Word"}]}]}]}}],"type":"Word"},{"text":"-eq","type":"Word"},{"text":"0","type":"Word"},{"text":"]","type":"Word"}]}]},"do":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"sleep","type":"Word"},"suffix":[{"text":"5","type":"Word"}]}]}}
echo "
⌛ Waiting for PostgreSQL to be ready..."
kubectl "wait" "--for=condition=ready" "pod" "--selector=db=polar-postgres" "--timeout=180s"
echo "
📦 Deploying Redis..."
kubectl "apply" "-f" "services\redis.yml"
sleep "5"
echo "
⌛ Waiting for Redis to be deployed..."
REM UNKNOWN: {"type":"While","clause":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"[","type":"Word"},"suffix":[{"text":"$(kubectl get pod -l db=polar-redis | wc -l)","expansion":[{"loc":{"start":0,"end":43},"command":"kubectl get pod -l db=polar-redis | wc -l","type":"CommandExpansion","commandAST":{"type":"Script","commands":[{"type":"Pipeline","commands":[{"type":"Command","name":{"text":"kubectl","type":"Word"},"suffix":[{"text":"get","type":"Word"},{"text":"pod","type":"Word"},{"text":"-l","type":"Word"},{"text":"db=polar-redis","type":"Word"}]},{"type":"Command","name":{"text":"wc","type":"Word"},"suffix":[{"text":"-l","type":"Word"}]}]}]}}],"type":"Word"},{"text":"-eq","type":"Word"},{"text":"0","type":"Word"},{"text":"]","type":"Word"}]}]},"do":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"sleep","type":"Word"},"suffix":[{"text":"5","type":"Word"}]}]}}
echo "
⌛ Waiting for Redis to be ready..."
kubectl "wait" "--for=condition=ready" "pod" "--selector=db=polar-redis" "--timeout=180s"
echo "
📦 Deploying RabbitMQ..."
kubectl "apply" "-f" "services\rabbitmq.yml"
sleep "5"
echo "
⌛ Waiting for RabbitMQ to be deployed..."
REM UNKNOWN: {"type":"While","clause":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"[","type":"Word"},"suffix":[{"text":"$(kubectl get pod -l db=polar-rabbitmq | wc -l)","expansion":[{"loc":{"start":0,"end":46},"command":"kubectl get pod -l db=polar-rabbitmq | wc -l","type":"CommandExpansion","commandAST":{"type":"Script","commands":[{"type":"Pipeline","commands":[{"type":"Command","name":{"text":"kubectl","type":"Word"},"suffix":[{"text":"get","type":"Word"},{"text":"pod","type":"Word"},{"text":"-l","type":"Word"},{"text":"db=polar-rabbitmq","type":"Word"}]},{"type":"Command","name":{"text":"wc","type":"Word"},"suffix":[{"text":"-l","type":"Word"}]}]}]}}],"type":"Word"},{"text":"-eq","type":"Word"},{"text":"0","type":"Word"},{"text":"]","type":"Word"}]}]},"do":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"sleep","type":"Word"},"suffix":[{"text":"5","type":"Word"}]}]}}
echo "
⌛ Waiting for RabbitMQ to be ready..."
kubectl "wait" "--for=condition=ready" "pod" "--selector=db=polar-rabbitmq" "--timeout=180s"
echo "
📦 Deploying Polar UI..."
kubectl "apply" "-f" "services\polar-ui.yml"
sleep "5"
echo "
⌛ Waiting for Polar UI to be deployed..."
REM UNKNOWN: {"type":"While","clause":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"[","type":"Word"},"suffix":[{"text":"$(kubectl get pod -l app=polar-ui | wc -l)","expansion":[{"loc":{"start":0,"end":41},"command":"kubectl get pod -l app=polar-ui | wc -l","type":"CommandExpansion","commandAST":{"type":"Script","commands":[{"type":"Pipeline","commands":[{"type":"Command","name":{"text":"kubectl","type":"Word"},"suffix":[{"text":"get","type":"Word"},{"text":"pod","type":"Word"},{"text":"-l","type":"Word"},{"text":"app=polar-ui","type":"Word"}]},{"type":"Command","name":{"text":"wc","type":"Word"},"suffix":[{"text":"-l","type":"Word"}]}]}]}}],"type":"Word"},{"text":"-eq","type":"Word"},{"text":"0","type":"Word"},{"text":"]","type":"Word"}]}]},"do":{"type":"CompoundList","commands":[{"type":"Command","name":{"text":"sleep","type":"Word"},"suffix":[{"text":"5","type":"Word"}]}]}}
echo "
⌛ Waiting for Polar UI to be ready..."
kubectl "wait" "--for=condition=ready" "pod" "--selector=app=polar-ui" "--timeout=180s"
echo "
⛵ Happy Sailing!
"