apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/sunithanbh007github/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/sunithanbh007github/order-service
  newTag: b50652f5be8ef1476c2eedf95e9224f3305515e4

replicas:
- count: 1
  name: order-service
